[package]
name = "ssdcg"
version = "1.0.0"
edition = "2018"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
derive_more = "0.99.16"
lalrpop-util = "0.19.6"
regex = "1"
rhai = "1.0.6"
structopt = "0.3.23"
